export enum RouteName {
  DASHBOARD = 'DASHBOARD',
  ROTATING_CUBE_O1 = 'ROTATING_CUBE_O1',
  STATIC_2D_02 = 'STATIC_2D_02',
  STATIC_2D_3D_03 = 'STATIC_2D_3D_03',
  PEDESTAL = 'PEDESTAL',
  BASE_SHADING = 'BASE_SHADING',
  TEXTURES = 'TEXTURES',
}
